name: Releaser

on:
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.12'
          
      - name: Make All
        run: |
          chmod a+x ./package.sh
          ./package.sh

      - name: Release
        uses: actions/upload-artifact@v4
        with:
          name: frp
          path: packages